#!/usr/bin/env bash
# Script that takes an IP as an argument and calls ping

if [[ $1 =~ ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}$ ]]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
