#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

if [ $# -ne 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
else
	case $1 in
		"start")
			bash manage_my_process
			grep -f "manage_my_process" > "/var/run/my_process.pid"
			echo "manage_my_process started"
			;;
		"stop")
			pid=$(cat /var/run/my_process.pid)
			kill -19 "$pid"
			rm "/var/run/my_process.pid"
			echo "manage_my_process stopped"
			;;
		"restart")
			pid=$(cat /var/run/my_process.pid)
			kill -19 "$pid"
			bash manage_my_process
			grep -f "manage_my_process" > "/var/run/my_process.pid"
			echo "manage_my_process restarted"
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
			;;
	esac
fi
