#!/usr/bin/env bash
# a Bash script that displays:
#+	The content of the current directory
#+	In a list format
#+	Where only the part of the name after the first dash is displayed

ls > list
a=$(cut -d "-" -f 2- list)
for i in $a
do
	echo "$i"
done
rm list
